apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic
  labels:
    app: config-server
    component: infrastructure
    tier: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        component: infrastructure
        tier: config
    spec:
      containers:
      - name: config-server
        image: springcommunity/spring-petclinic-config-server:3.2.0
        ports:
        - containerPort: 8888
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: petclinic
  labels:
    app: config-server
    component: infrastructure
spec:
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888
    name: http
  type: ClusterIP
