global:
  namespace: ecommerce
  imageRegistry: your-registry
  imageTag: v1.0.0

backend:
  enabled: true
  replicaCount: 3
  image:
    repository: ecommerce-backend
    tag: v1.0.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: ecommerce-frontend
    tag: v1.0.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

database:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  service:
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
  alertmanager:
    enabled: true

networkPolicies:
  enabled: true

secrets:
  database:
    url: "postgresql://postgres:password@ecommerce-database:5432/ecommerce"
  jwt:
    secret: "your-jwt-secret-key"
