apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic
  labels:
    app: discovery-server
    component: infrastructure
    tier: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
        component: infrastructure
        tier: discovery
    spec:
      containers:
      - name: discovery-server
        image: springcommunity/spring-petclinic-discovery-server:3.2.0
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic
  labels:
    app: discovery-server
    component: infrastructure
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
    name: http
  type: ClusterIP
