apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app: admin-server
    component: monitoring
    tier: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
        component: monitoring
        tier: admin
    spec:
      containers:
      - name: admin-server
        image: springcommunity/spring-petclinic-admin-server:3.2.0
        ports:
        - containerPort: 9090
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: DISCOVERY_SERVER_URL
          value: "http://discovery-server:8761/eureka"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic
  labels:
    app: admin-server
    component: monitoring
spec:
  selector:
    app: admin-server
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  type: ClusterIP
