apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: petclinic
  labels:
    app: mysql
    component: database
type: Opaque
data:
  # Base64 encoded values
  # username: petclinic (cGV0Y2xpbmlj)
  # password: petclinic123 (cGV0Y2xpbmljMTIz)
  # root-password: rootpassword123 (cm9vdHBhc3N3b3JkMTIz)
  username: cGV0Y2xpbmlj
  password: cGV0Y2xpbmljMTIz
  root-password: cm9vdHBhc3N3b3JkMTIz
