apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: petclinic-daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  template:
    includedNamespaces:
    - petclinic
    storageLocation: default
    ttl: 720h0m0s  # 30 days retention
---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: petclinic-manual-backup
  namespace: velero
spec:
  includedNamespaces:
  - petclinic
  storageLocation: default
  ttl: 720h0m0s
